name: Daily Coding Contribution

# When to run this workflow
on:
  schedule:
    # Runs daily at 10:00 UTC (adjust for your timezone)
    - cron: '0 10 * * *'
  workflow_dispatch: # Allows manual triggering from GitHub website

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Download the repository code
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    # Step 3: Run our update script
    - name: Run daily update script
      run: python update_readme.py
    
    # Step 4: Configure Git user (required for commits)
    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Daily Coding Bot"
    
    # Step 5: Commit and push changes
    - name: Commit and push changes
      run: |
        git add README.md
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "🤖 Daily coding fact update - $(date +'%Y-%m-%d')"
          git push
        fi
